### ISSUE TITLE
Doesn't run on CentOS 7?

### ISSUE THREAD

**Issue by durina** [fjossinet/RNArtist#10]
Hey!
This software runs on my laptop (Ubuntu 20.04), and fails to start up when I try to run it on our workstation (CentOS 7). Tried it on two independent workstations.
This is the error I get when I run `mvn clean package`:

```
Plenty download success...

[WARNING] Using experimental Kotlin incremental compilation
[INFO] Non-incremental compilation will be performed: NO_BUILD_HISTORY
[INFO] Kotlin compile iteration: /path/to/RNArtist/src/main/kotlin/RNArtist.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/Mediator.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Canvas2D.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Editor.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnar
tist/gui/EmbeddedDBGUI.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Explorer.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/JunctionKnob.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/JunctionKnobFX.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/ProjectsPanel.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/SelectionShape.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Settings.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/SplashWindow.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/WebBrowser.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/Button.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ColorPicker.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/HBox.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ScriptEditor.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/TextField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/TypeChooser.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/io/ChimeraDriver.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/io/ChimeraXDriver.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/io/EmbeddedDB.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/io/Utils.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/DrawingLoaded.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/ExplorerItem.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/BpseqKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/BracketNotationKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ClosedCurly.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ColorField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ColorKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/CtKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/DSLElement.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/DSLKeyword.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/DSLParameter.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/DataKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/FileField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/FloatField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/HideKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/IntegerField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/JunctionKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/LayoutKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/LineKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/LocationKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/NewLine.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/OpenedCurly.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/Operator.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/OptionalDSLKeyword.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/OptionalDSLParameter.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ParameterField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/RNArtistKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/RfamKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ScriptTab.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/SecondaryStructureKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/SequenceBnParameter.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ShowKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/StockholmKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/StringValueWithQuotes.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/StringWithQuotes.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/StringWithoutQuotes.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ThemeKw.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/TypeField.kt, /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/model/editor/ViennaKw.kt
[INFO] Exit code: COMPILATION_ERROR
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Editor.kt: (17, 8) Unresolved reference: netscape
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Editor.kt: (118, 20) Unresolved reference: JSObject
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ScriptEditor.kt: (100, 45) Function invocation 'isEmpty(...)' expected
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ScriptEditor.kt: (100, 45) Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public inline fun <T> Array<out TypeVariable(T)>.isEmpty(): Boolean defined in kotlin.collections
public inline fun BooleanArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun ByteArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun CharArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun CharSequence.isEmpty(): Boolean defined in kotlin.text
public inline fun DoubleArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun FloatArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun IntArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun LongArray.isEmpty(): Boolean defined in kotlin.collections
public inline fun ShortArray.isEmpty(): Boolean defined in kotlin.collections
[INFO] Compiled 62 Kotlin files using incremental compiler
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:31.775s   
[INFO] Finished at: Thu Dec 23 16:00:40 IST 2021
[INFO] Final Memory: 182M/516M 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.6.0:compile (compile) on project rnartist: Compilation failure: Compilation failure:
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Editor.kt:[17,8] Unresolved reference: netscape
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/Editor.kt:[118,20] Unresolved reference: JSObject
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ScriptEditor.kt:[100,45] Function invocation 'isEmpty(...)' expected
[ERROR] /path/to/RNArtist/src/main/kotlin/io/github/fjossinet/rnartist/gui/editor/ScriptEditor.kt:[100,45] Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
[ERROR] public inline fun <T> Array<out TypeVariable(T)>.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun BooleanArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun ByteArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun CharArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun CharSequence.isEmpty(): Boolean defined in kotlin.text
[ERROR] public inline fun DoubleArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun FloatArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun IntArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun LongArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] public inline fun ShortArray.isEmpty(): Boolean defined in kotlin.collections
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
And when I anyway proceed to run `mvn exec:exec`, it spits out an error quoted below:
```
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:982)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:929)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:457)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.549s
[INFO] Finished at: Thu Dec 23 16:02:01 IST 2021
[INFO] Final Memory: 14M/293M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rnartist: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
More information
`lsb_release -a`

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```
`uname -r`
```
3.10.0-1160.45.1.el7.x86_64
```

**Comment by fjossinet** [comment]
Hi. 

Concerning the issue with the message "Unrecognized option: --module-path", the module feature does exist since Java 9. So i think that your jdk 1.8 is too old. Which java version are you using with your Ubuntu? I suggest to use at least jdk 11. 

Let me know

Best

**Comment by durina** [comment]
> Concerning the issue with the message "Unrecognized option: --module-path", the module feature does exist since Java 9. So i think that your jdk 1.8 is too old.

Hey, I looked into this issue, installed JRE11 package (`java-11-openjdk-devel`) and even that this version as the default java (`sudo alternatives --config java`) when I re-tried installation, and I get a similar error.

>Which java version are you using with your Ubuntu?

The java in my Ubuntu system is `openjdk version "11.0.13"`.

Thanks for taking your time to look at it!

Cheers!

**Comment by fjossinet** [comment]
Hi. Did you find the problem with CentOS?

**Comment by fjossinet** [comment]
Hi. Did you install the last version from this page: https://www.jdeploy.com/~rnartist

Could you give it a try because many things have been modified and fixed. Thanks
