### ISSUE TITLE
RNArtist on Mac

### ISSUE THREAD

**Issue by wxh180** [fjossinet/RNArtist#3]
I tried to run it on my Mac and got the following error:
Error: Unable to access jarfile lib/rnartist-1.0.jar

Please let me know how I can fix this problem?

**Comment by fjossinet** [comment]
I think that you launched the script from project_root_dir/RNArtist. You need first to compile and package the project with maven (mvn clean package) and then launch the script from project_root_dir/target/RNArtist. You can also use maven to launch RNArtist by typing mvn exec:exec. A fully packaged release will be available soon.

**Comment by wxh180** [comment]
I see. I missed that step. However, after a full build with maven. I still got some errors when launching the code:
taylorlab-imac:RNArtist wei$ ./launch_rnartist_for_MacOSX.command 
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: lib/ikonli-core-12.1.0.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 55.0

**Comment by fjossinet** [comment]
this seems a problem between your java version to run RNArtist and the one used to compile this dependency. Which java version are u using?

**Comment by wxh180** [comment]
This is the java version from MacOS
taylorlab-imac:target wei$ java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

And I used HomeBrew to install maven

**Comment by wxh180** [comment]
Yes. The version is different. How to fix this problem?

taylorlab-imac:target wei$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 15.0.1, vendor: N/A, runtime: /Volumes/Programs/packages/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by fjossinet** [comment]
You should run RNArtist with maven to have the same java version. The script launch_rnartist_for_MacOSX.command uses your default java. So from the root dir of the project, try  "mvn exec:exec"

**Comment by wxh180** [comment]
Had another error with mvn:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.103 s
[INFO] Finished at: 2021-02-02T10:06:58-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rnartist: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rnartist: Command execution failed.

**Comment by fjossinet** [comment]
oops my fault: mvn package exec:exec

**Comment by wxh180** [comment]
unfortunately, this does not work either.

#####
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.043 s
[INFO] Finished at: 2021-02-02T10:27:54-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rnartist: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
#######

Thanks for your patient!

**Comment by fjossinet** [comment]
ok, the full try ;-) 

mvn clean package exec:exec

**Comment by wxh180** [comment]
Still the same error T_T
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.035 s
[INFO] Finished at: 2021-02-02T10:36:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rnartist: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]

**Comment by fjossinet** [comment]
The problem is still the java version. mvn exec:exec still use the lowest version. I see several options. 
Try this one 
*  in target/RNArtist edit the file launch_rnartist_for_MacOSX.command
*  modify the last line to have  "/Volumes/Programs/packages/openjdk/15.0.1/libexec/openjdk.jdk/Contents/Home/bin/java" instead of just "java"
* save and run this script

**Comment by wxh180** [comment]
I can see the icon pops up on deck but then disappears again. Here is the log:

taylorlab-imac:RNArtist wei$ ./launch_rnartist_for_MacOSX.command 
java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at io.github.fjossinet.rnartist.io.UtilsKt.getImage(Utils.kt:13)
	at io.github.fjossinet.rnartist.Mediator.<init>(Mediator.kt:72)
	at io.github.fjossinet.rnartist.RNArtist.start(RNArtist.java:107)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type java.awt.image.RenderedImage
	at io.github.fjossinet.rnartist.Mediator.<init>(Mediator.kt:72)
	at io.github.fjossinet.rnartist.RNArtist.start(RNArtist.java:107)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[Thread-4] INFO org.dizitart.no2.Nitrite - Nitrite database has been closed successfully.

**Comment by fjossinet** [comment]
Yes, good point. The last commits changed something producing an issue but only for a fresh install. I commit my modifications this evening and it should work. Sorry for the delay.

**Comment by wxh180** [comment]
Thanks! I really appreciate that your help with go through this. I will check it out again tomorrow. And look forward to using this amazing new RNA toolkit!

**Comment by fjossinet** [comment]
I pushed the new code to fix the issue you found. Try now mvn clean package exec:exec

**Comment by wxh180** [comment]
It works beautifully now. Thanks a bunch!

**Comment by fjossinet** [comment]
Super cool! Thank you for your feedback!
