### ISSUE TITLE
json saving errors

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#6]
Hi,

I would like to save all my setting in RNArtists in json format.

However, when I loaded the JSON format next time, it came errors, the stacktrace was:

```
java.lang.IllegalArgumentException: No enum constant io.github.fjossinet.rnartist.core.model.ConnectorId.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at rnartistcore@0.2.9-SNAPSHOT/io.github.fjossinet.rnartist.core.model.ConnectorId.valueOf(Drawings.kt)
	at rnartistcore@0.2.9-SNAPSHOT/io.github.fjossinet.rnartist.core.model.io.ParsersKt.parseProject$lambda-19(parsers.kt:312)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at rnartistcore@0.2.9-SNAPSHOT/io.github.fjossinet.rnartist.core.model.io.ParsersKt.parseProject(parsers.kt:313)
	at rnartistcore@0.2.9-SNAPSHOT/io.github.fjossinet.rnartist.core.model.io.ParsersKt.parseJSON(parsers.kt:292)
	at rnartist@1.0/io.github.fjossinet.rnartist.RNArtist$1$loadData$1.call(RNArtist.kt:110)
	at rnartist@1.0/io.github.fjossinet.rnartist.RNArtist$1$loadData$1.call(RNArtist.kt:104)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Could you please give some suggestions?

My best,

**Comment by fjossinet** [comment]
Hi. I did not test the json saving since a while now (more focused on svg export). I’m gonna giving a try on my side and come back to u soon.

**Comment by fjossinet** [comment]
Hi. This issue should be fixed now.
