### ISSUE TITLE
the commandline (Editor) doesn't work

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#8]
Hi, fjossinet,

The command-line (Editor) seems cannot render the RNA structure in this new version.

when I click the run the editor butter, the error shows:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
javax.script.ScriptException: ERROR Unable to initialize repl compiler:
  DEBUG Using JVM IR backend
  ERROR java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError: java.lang.IllegalStateException: Unable to initialize repl compiler:
  DEBUG Using JVM IR backend
  ERROR java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
	at kotlin.compiler.embeddable@1.5.31/org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:104)
	at kotlin.compiler.embeddable@1.5.31/org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
	at kotlin.scripting.jvm.host@1.5.31/kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:94)
	at kotlin.compiler.embeddable@1.5.31/org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at rnartist@1.0/io.github.fjossinet.rnartist.io.github.fjossinet.rnartist.gui.Editor.lambda-4$lambda-3(Editor.kt:52)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)


```
My best,

**Comment by fjossinet** [comment]
The editor will be removed (and perhaps replaced with something else). It was a test. I not like it so much ;-)

**Comment by MingleiYang** [comment]
Hi, fjossinet,

oh, No. if you remove it, how could we label the SHAPE reactivity value?

do you add new utility there? the advantage of the editor there is that we can put the SHAPE reactivity values and interactively change the layout of the plot.

**Comment by fjossinet** [comment]
Hi.

Sorry for this late reply. I'm working on a new editor. It should be ready soon. I published two insights:

[https://twitter.com/rnartist_app/status/1471403003945103360?s=20](url)

[https://twitter.com/rnartist_app/status/1472183112947978245?s=20](url)

**Comment by fjossinet** [comment]
Hi, 
I have updated RNArtistCore with the new editor. Git it a try, the data should work (between operator not ready, but gt, lt and eq should work). You can have a look at this gist you can load from the editor menu (https://gist.github.com/fjossinet/dfd731d4831ea8ffb6eae7c90d2c4e87)

**Comment by MingleiYang** [comment]
Thank you very much, I am gonna give it a go.

**Comment by fjossinet** [comment]
I'm closing this issue then. Post a new one if you find issues with the new script editor.
